### ISSUE TITLE
Can't get plot for some tv shows

### ISSUE THREAD

**Issue by Apollo2000** [FabianBeiner/PHP-IMDB-Grabber#121]
Hello,

Trying to get new tv shows plot return null.
For example: tt9561862, tt7459986, tt8390342, tt8259142

Thank you for your great class!

**Comment by FabianBeiner** [comment]
The script can't fetch what isn't there. ;) `tt8390342` prints a plot, because it is listed (see `https://www.imdb.com/title/tt8390342/reference` and search for `Plot Summary`.

However, if you're after `FBI agent Will Keaton enlists the most notorious traitor in American history to help catch a spy.` (listed on the top of the page): This is the summary, but there is no real or easy way to fetch it because it is not listed between any specific HTML element and is different on many pages.

Sorry, there is nothing I can do at the moment. If you find a decent and working regex for the summary, please let me know and open a pull request. Thanks!
