### ISSUE TITLE
Get Director's image

### ISSUE THREAD

**Issue by lastwall** [FabianBeiner/PHP-IMDB-Grabber#125]
Hi

first thanks for your great effort
would consider working on getting the Director's image too?
or if is there any way to get the image of director now let me know

regards

**Comment by FabianBeiner** [comment]
Hey @lastwall, 

I am so sorry for the late delay! I completely missed this Issue. Currently, there is no way to fetch the image of the Director of the movie, since it is not listed on the Reference page. You would need to run another call to the page of the Director and get it from there.

I won't add that to the library, because it is a massive overhead for a small improvement.
