### ISSUE TITLE
missing function and feature requests

### ISSUE THREAD

**Issue by OliverLeitner** [FabianBeiner/PHP-IMDB-Grabber#65]
hi Fabian

would it be possible to get getBudget(); back into the class?

somehow the imdb curl fetcher now grabs a subset of imdb.com and the budget info is no longer part of that subset, was there a reason for that?

also, if it would be possible, i would love to see two more imdb contents:

getMetascore();
getPGRating();

**Comment by OliverLeitner** [comment]
getBudget regex:

const IMDB_BUDGET       = '~Budget:</h4>(.*)<span~Ui';

getMetascore regex:

const IMDB_METASCORE    = '~provided by Metacritic.com" >(.*)</a>~Ui';

getPGRating regex:

const IMDB_PGRATING     = '~itemprop="contentRating" content="(.*)">~Ui';

**Comment by FabianBeiner** [comment]
Hey @OliverLeitner,
sorry for the detail in my answer, I've been pretty busy.

With the latest version I switched to the `/combined` page (eg. http://www.imdb.com/title/tt0401711/combined). Since that one is not updated that often, the script will (and does!) run longer without any modifications. Sadly, this also meant that I had to remove a few functions, because their information isn't listed on this page anymore. This also means there is no way to parse Metascore, PG or anything from main page which isn't listed on the combined one. Unless you're going to do a second request for this information.

Best,
Fabian
