### ISSUE TITLE
Plot is incomplete

### ISSUE THREAD

**Issue by BrianSpan** [FabianBeiner/PHP-IMDB-Grabber#72]
I don't know if this is considered a bug fix or a feature request.

When you scrape the plot from the '/combined' page of IMDB, it just shows a truncated version ending with an ellipsis (...). An example is tt0040003 (Women in the Night 1948).

A better place to get the entire plot would be the '/plotsummary' page. You can see the difference in size with the example I gave (http://www.imdb.com/title/tt0040003/plotsummary). You can use '/<p class=\"plotSummary\">(.*)<\/p>/is' as the regex filter.

(Of course, some plot summaries still end or use an ellipsis for effect: see tt0293261 and tt0830558 .)

**Comment by FabianBeiner** [comment]
Hi @BrianSpan!

Requests like these came up a few times already. Up until now I never implemented them, because this would mean another full request to the IMDb page. Someone once implemented something like this for the [`getAkas`](https://github.com/FabianBeiner/PHP-IMDB-Grabber/blob/master/imdb.class.php#L300) method, which I pulled in, but sometimes regretted because I just don’t like doing more requests for stuff like this.

Then again, you could implement it for yourself if it is important for you. As mentioned, look at the `getAkas` method, this might help you.
