### ISSUE TITLE
Poster cannot load.

### ISSUE THREAD

**Issue by BiegerRodriguez** [FabianBeiner/PHP-IMDB-Grabber#74]
My pictures cannot be load:

I do it like this:
$IMDB = new IMDB("'".$name."'");
$poster = $IMDB->getPoster('big', true);
$html_string = 
"<td><img class='img-responsive' 
alt='$name' src='$poster' width='96px' height='142px'>
 </td>";

The html code is for the example of Pulp Fiction is:

<img class="img-responsive" alt="Pulp Fiction" src="http://ia.media-imdb.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@.jpg" width="96px" height="142px">

And the output looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/12819454/12179193/c099cb2c-b575-11e5-8a73-3a85fbf54665.PNG)

Edit: For a reason i dont know on this website it work.
So can you help me maybe why it works here and not at my page.

**Comment by BrianSpan** [comment]
(I'm not the creator/maintainer of the software; just another user.) The HTML didn't quite display properly but I'm confused. You set 'download' to 'true' but you are using the URL to IMDB directly. You should be able to use the local path to where you downloaded the image.

**Comment by BiegerRodriguez** [comment]
But the name of the downloaded posters are just ids. How i get these ids?

**Comment by BrianSpan** [comment]
The id is the tt# that IMDB assigned. You can get that from the URL. Here's a quick code. You can clean up as needed::

$url='http://www.imdb.com/title/tt0203009/';  //sample URL
preg_match('/t{2}(\d{7})/i',$url,$match);
$poster=$match[1].'.jpg';  //this is the name of the poster

**Comment by FabianBeiner** [comment]
Uhm, this issue revealed a problem with the current `getPoster` method. Basically, it always returned the link to IMDb directly and not to the local version, because some path check *(probably)* failed. Not a big issue, but I’ve fixed it now.

In the next release, the `getPoster` method defaults to `false` for the downloading part. So you have to enable the download of the image, which is probably what most users want anyway. I also made the private variable `$iId` public, so you can use `$oIMDB->iId` to get the ID of the movie. But the method now returns the local path to the posters directory, but you might have to prepend something (like `<img src="../<?= $oIMDB->getPoster('small', true) ?>">`).
