### ISSUE TITLE
Year not grabbed when movie title has a duplicate

### ISSUE THREAD

**Issue by dna75** [FabianBeiner/PHP-IMDB-Grabber#75]
When there are movies with the same title I notice that the year get's included in the movie title when scraped. For example 'tt3276924'. When I scrape this title the movie title becomes 'Heist (2015/III)' and the release date is 'N/A'.

**Comment by FabianBeiner** [comment]
I had this issue before. But I can’t fix it. For example, if I run this movie, I get the following results:

![Screenshot](http://abload.de/img/screenshot-localhost23vrzo.png)

So the release date is working, which is fine. But I can't split anything from the movie title, because there might be movies that have something important in the braces.

Sorry I can’t help you with this issue.
