### ISSUE TITLE
AKAS

### ISSUE THREAD

**Issue by maknol** [FabianBeiner/PHP-IMDB-Grabber#90]
Hi, another issues, this time with getAkas, is there chance to get full akas? At this time we get short list.
Example:
http://www.imdb.com/title/tt0204137/reference and http://www.imdb.com/title/tt0204137/releaseinfo?ref_=tt_dt_dt#akas

**Comment by FabianBeiner** [comment]
No, **I** won't implement that in the core of the script, but you should feel free to do so.

I don't want to do another request for anything else, because it's a) slowing down the script even more and b) one more request to IMDb you actually shouldn't do. ;) People wished for all kind of information from other IMDb pages before, but as said, I won't implement it. Sorry.
